-- Create second table requested by user
-- Table: public.svr_list_database

create table if not exists public.svr_list_database (
  id bigint generated by default as identity primary key,
  unique_key text unique,
  call_id text,
  location text,
  engineer_name text,
  workshop_onsite text,
  call_type text,
  primary_secondary_engineer text,
  complaint text,
  customer_name text,
  contact_number text,
  machine_no text,
  hmr text,
  breakdown_status text,
  mc_model text,
  installation_date date,
  site_location text,
  deputation_date date,
  deputation_time text,
  engineer_onsite_time text,
  work_completion_date date,
  work_completion_time text,
  labour_charge numeric(12,2),
  distance numeric(12,2),
  da_applied numeric(12,2),
  ta_amt_approved numeric(12,2),
  da_amt_approved numeric(12,2),
  total_tada numeric(12,2),
  date date,
  list_id text,
  svr_number text,
  list_creation_date date,
  invoice_number text,
  passed_amount numeric(12,2),
  verified_datetime timestamp with time zone,
  passed_datetime timestamp with time zone,
  created_at timestamp with time zone not null default now()
);

create index if not exists idx_svr_list_database_list_id
  on public.svr_list_database(list_id);

create index if not exists idx_svr_list_database_date
  on public.svr_list_database(date);

create index if not exists idx_svr_list_database_engineer
  on public.svr_list_database(engineer_name);
